-- =============================================================
-- Accounting Rules Table Setup
-- ObjectID is the primary key, generated by ACCOUNTING_RULES_SEQ.
-- Run this ONCE before running the migration simulation.
--
-- Run in DBeaver: execute each statement separately (Ctrl+Enter)
-- =============================================================

-- STEP 1: Drop existing objects (skip if first-time setup)
-- DROP SEQUENCE ACCOUNTING_RULES_SEQ;
-- DROP TABLE ACCOUNTING_RULES;

-- STEP 2: Create the sequence (simulates on-premises sequence starting at 1)
CREATE SEQUENCE ACCOUNTING_RULES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- STEP 3: Create the table
CREATE TABLE ACCOUNTING_RULES (
    OBJECT_ID       NUMBER          PRIMARY KEY,
    RULE_CODE       VARCHAR2(50)    NOT NULL,
    RULE_DESCRIPTION VARCHAR2(500),
    ACCOUNT_ID      VARCHAR2(100),
    CREATED_BY      VARCHAR2(100),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE'
);

-- STEP 4: Verify
SELECT 'ACCOUNTING_RULES table and ACCOUNTING_RULES_SEQ created.' AS STATUS FROM DUAL;
