"""
Accounting Rules Processor

Reads new accounting rules from a list and inserts them into Oracle
using the ACCOUNTING_RULES_SEQ sequence for primary key generation.

After the database migration, the sequence is out of sync with the
actual max OBJECT_ID — causing ORA-00001 unique constraint violations
when users try to add new records.

Errors are automatically logged to APP_ERROR_LOGS so the MCP server
can query them and the AI can suggest the fix.
"""
import logging
import sys
import os
from datetime import datetime

logger = logging.getLogger(__name__)

# New accounting rules that users are trying to add post-migration
NEW_RULES = [
    {
        "rule_code": "RULE-009",
        "rule_description": "Fixed Asset Depreciation Rule",
        "account_id": "ACC-009",
        "created_by": "user_001",
    },
    {
        "rule_code": "RULE-010",
        "rule_description": "Revenue Recognition Rule",
        "account_id": "ACC-010",
        "created_by": "user_002",
    },
    {
        "rule_code": "RULE-011",
        "rule_description": "Expense Accrual Rule",
        "account_id": "ACC-011",
        "created_by": "user_003",
    },
    {
        "rule_code": "RULE-012",
        "rule_description": "Foreign Exchange Revaluation Rule",
        "account_id": "ACC-012",
        "created_by": "user_004",
    },
]


class AccountingRulesProcessor:
    """Inserts new accounting rules into Oracle using the sequence for OBJECT_ID."""

    def __init__(self, oracle_client, error_logger=None):
        self._oracle = oracle_client
        self._error_logger = error_logger

    def insert_rule(self, rule: dict) -> bool:
        """
        Insert a single accounting rule.
        Uses ACCOUNTING_RULES_SEQ.NEXTVAL for the primary key.
        """
        sql = """
            INSERT INTO ACCOUNTING_RULES
                (OBJECT_ID, RULE_CODE, RULE_DESCRIPTION, ACCOUNT_ID, CREATED_BY, CREATED_AT)
            VALUES
                (ACCOUNTING_RULES_SEQ.NEXTVAL, :rule_code, :rule_description,
                 :account_id, :created_by, :created_at)
        """
        params = {
            "rule_code": rule["rule_code"],
            "rule_description": rule["rule_description"],
            "account_id": rule["account_id"],
            "created_by": rule["created_by"],
            "created_at": datetime.utcnow(),
        }

        try:
            with self._oracle._get_connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(sql, params)
                conn.commit()
            print(f"  [OK] Inserted rule: {rule['rule_code']}")
            return True

        except Exception as e:
            error_msg = str(e)
            print(f"  [ERROR] Failed to insert {rule['rule_code']}: {error_msg}")

            if self._error_logger:
                self._error_logger.log_error(
                    error=e,
                    error_code="ORA-00001" if "unique constraint" in error_msg.lower() else "DB-INSERT-ERR",
                    module_name="AccountingRulesProcessor.insert_rule",
                    user_id=rule.get("created_by", "unknown"),
                    extra_context=(
                        f"rule_code={rule['rule_code']} | "
                        f"table=ACCOUNTING_RULES | "
                        f"sequence=ACCOUNTING_RULES_SEQ | "
                        f"error=Sequence out of sync after migration — "
                        f"OBJECT_ID generated by sequence already exists in table"
                    ),
                )
            return False

    def process_all(self) -> dict:
        """Insert all new rules, return summary."""
        print(f"\nInserting {len(NEW_RULES)} new accounting rules...\n{'─' * 50}")
        success, failed = 0, 0

        for rule in NEW_RULES:
            if self.insert_rule(rule):
                success += 1
            else:
                failed += 1

        print(f"\n{'─' * 50}")
        print(f"  Inserted: {success}  |  Failed: {failed}")
        return {"success": success, "failed": failed}
